version: "3"
services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: always
    networks:
      - test-server-network
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
      - redis-data:/bitnami/redis
networks:
  test-server-network:
    external: false
volumes:
  redis-data:
