version: "3"
services:
  redis:
    image: redis:7.0.10-alpine
    container_name: redis
    restart: always
    networks:
      - test-server-network
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - syslog-ng-data:/config/log
      - ./syslog-ng.conf:/config/syslog-ng.conf
networks:
  test-server-network:
    external: false
volumes:
  syslog-ng-data:
