version: "3"
services:
  nginx-download:
    image: nginx:1.23.3
    container_name: nginx-download
    restart: always
    networks:
      - test-server-network
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./download.conf:/etc/nginx/conf.d/download.conf
      - ./download:/home/share
networks:
  test-server-network:
    external: false
# volumes:
#   syslog-ng-data:
