version: "3"
services:
  ftpd:
    image: teezily/ftpd
    container_name: ftpd
    restart: always
    privileged: true
    networks:
      - test-server-network
    ports:
      - "21:21/tcp"
      - "65000-65004:65000-65004"
    environment:
      - FTP_USER=admin
      - FTP_PASSWORD=admin
      - TZ=Asia/Shanghai
      - HOST=localhost
      - PASV_MIN_PORT=65000
      - PASV_MAX_PORT=65004
networks:
  test-server-network:
    external: false
