version: "3"
services:
  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka-exporter
    network_mode: host
    command:
      - "--kafka.server=${KAFKA_HOST}:9092"
      - '--sasl.enabled'
      - '--sasl.username=broker'
      - '--sasl.password=${password}'
      - '--sasl.mechanism=plain'
    ports: 
        - '9308:9308'
    restart: always