apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitor
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"
    scrape_configs:
      - job_name: "concul_internal_service"
        metrics_path: '/v1/agent/metrics'
        params:
          format: ['prometheus']
        consul_sd_configs:
          - server: 'consul-server-headless.monitor.svc.cluster.local:8500'
            services: ['consul']
        relabel_configs:
          - source_labels: [__address__]
            regex: (\d+\.\d+\.\d+\.\d+)\:8300
            target_label: __address__
            replacement: ${1}:8500
      - job_name: "concul_external_service"
        consul_sd_configs:
          - server: 'consul-server-headless.monitor.svc.cluster.local:8500'
            services: []
