apiVersion: v1
kind: Service
metadata:
  name: consul-client-external
  labels:
    app: consul-client
  namespace: monitor
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30083
    name: http-port
  - port: 8500
    targetPort: 8500
    nodePort: 30084
    name: ui-port
  - port: 8300
    targetPort: 8300
    nodePort: 30085
    name: server
  selector:
    app: consul-client
---
apiVersion: v1
kind: Service
metadata:
  name: consul-client-headless
  labels:
    app: consul-client
  namespace: monitor
spec:
  clusterIP: None
  ports:
  - port: 8080
    name: http-port
  - port: 8500
    name: ui-port
  - port: 8300
    name: server
  selector:
    app: consul-client
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-client-conf
  labels:
    name: consul-client-conf
  namespace: monitor
data:
  config.json: |-
    {
        "server": false,
        "datacenter": "Us-Central",
        "data_dir": "/var/consul",
        "log_level": "INFO",
        "enable_syslog": true,
        "leave_on_terminate": true,
        "start_join": [
          "consul-server-0.consul-server-headless.$(NAMESPACE).svc.cluster.local"
          "consul-server-1.consul-server-headless.$(NAMESPACE).svc.cluster.local"
          "consul-server-2.consul-server-headless.$(NAMESPACE).svc.cluster.local"
        ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-client
  namespace: monitor
  labels:
    app: consul-client
spec:
  selector:
    matchLabels:
      app: consul-client
  replicas: 1
  template:
    metadata:
      labels:
        app: consul-client
    spec:
      volumes:
        - name: consul-client-data-volume
          emptyDir: {}
      containers:
        - name: consul-client
          image: consul:latest
          args:
            - "agent"
            - "-client=0.0.0.0"
            - "-data-dir=/consul/data"
            - "-bind=0.0.0.0"
            - "-retry-join=consul-server-0.consul-server-headless.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-server-1.consul-server-headless.$NAMESPACE.svc.cluster.local"
            - "-advertise=$(PODIP)"
            - "-domain=cluster.local"
            - "-disable-host-node-id"
          env:
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: consul-client-data-volume
              mountPath: /consul/data
          resources:
            limits:
              cpu: 1
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500M
          ports:
            - containerPort: 8080
              name: http-port
            - containerPort: 8500
              name: ui-port
            - containerPort: 8400
              name: alt-port
            - containerPort: 53
              name: udp-port
            - containerPort: 8443
              name: https-port
            - containerPort: 8301
              name: serflan
            - containerPort: 8302
              name: serfwan
            - containerPort: 8600
              name: consuldns
            - containerPort: 8300
              name: server
