version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    user: root
    container_name: prometheus
    env_file:
      - .env
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules:/etc/prometheus/rules
      - prometheus-volume:/prometheus
    restart: always
    networks:
      - monitor
  grafana:
    image: grafana/grafana:latest
    user: root
    container_name: grafana
    depends_on:
      - prometheus
    env_file:
      - .env
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-volume:/var/lib/grafana
    restart: always
    ports:
      - '3000:3000'
    networks:
      - monitor
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    env_file:
      - .env
    depends_on:
      - prometheus
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
      - ./alertmanager/templates:/etc/alertmanager/templates
    networks:
      - monitor
    restart: always
  dingding-webhook:
    build: https://github.com/zzsuki/dingding-robot.git
    container_name: dingding-webhook
    env_file:
      - .env
    ports:
      - '8000:8000'
    restart: always
    networks:
      - monitor
volumes:
  prometheus-volume:
  grafana-volume:
networks:
  monitor:
    driver: bridge