version: "3"
services:
  snmptrapd:
    image: sig9/snmptrapd
    container_name: snmptrapd
    restart: always
    networks:
      - test-server-network
    ports:
      - "162:162/udp"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./snmptrapd.conf:/etc/snmp/snmptrapd.conf
networks:
  test-server-network:
    external: false
